import { Application, Request, Response, Router } from "express";
import { AuthHandler } from "../express/auth";

/** Base typing for a list of methods */
type BaseMethods<H> = { [MethodName: string]: (handle: H, ...args: any) => any };

/** Handle generated by the router, containing all necessary information */
export interface RequestHandle {
    userUID: string | null;
    req: Request;
    res: Response;
}

/** Builds a router that will bind all routes of data to routes */
export function buildAPIRouter<Methods extends BaseMethods<RequestHandle>>(api: Methods): Router {
    const router: Router = Router();

    router.post("/:method", async (req, res) => {
        const methodName: keyof Methods = req.params.method;
        const args: any[] = req.body ?? [];
        try {
            const method = api[methodName];
            if (method == null) {
                res.status(404).json({ error: `No method named ${methodName as string}()` });
                return;
            }
            const handle: RequestHandle = {
                req, res,
                userUID: AuthHandler.getUserUID(req)
            };
            let result = await method(handle, ...args);
            if (result === void (0)) {
                res.json(null); // No content
            } else {
                res.json(result ?? null);
            }
        } catch (err) {
            console.error(`Error while calling ${methodName as string} with args: ${JSON.stringify(args)}`);
            console.error(err);
            res.status(500).json({ error: new String(err) });
        }
    });

    return router;
}

/** 
 * Simply register an API on the application 
 * url MUST start with a /
 */
export function registerAPI<Methods extends BaseMethods<RequestHandle>>(app: Application, url: string, api: Methods): void {
    console.log(`Registered /${url}/[${Object.keys(api).join(", ")}]`);
    app.use(`/${url}`, buildAPIRouter(api));
}